### ISSUE TITLE
cssOutputFilename not working

### ISSUE THREAD

**Issue by Mytakeon** [EMH333/esbuild-svelte#127]
**Describe the bug**
Setting the `cssOutputfilename` in the compiler options has no effect.

**To Reproduce**
Add the css filename option in the example:

```js
import { build } from "esbuild";
import sveltePlugin from "esbuild-svelte";

build({
  entryPoints: ["./entry.js"],
  mainFields: ["svelte", "browser", "module", "main"],
  bundle: true,
  outfile: "./dist/bundle.js",
  plugins: [
    sveltePlugin({
      compilerOptions: { cssOutputFilename: "foo.css" },
    }),
  ],
}).catch((err) => {
  console.error(err);
  process.exit(1);
});

```
**Expected behavior**
The `dist` folder should contain `bundle.js` and `foo.css`, but it contains `bundle.js` and `bundle.css`

**Screenshots**

**Environment (please complete the following information):**

- esbuild-svelte version: 0.7.0
- esbuild version: 0.14.32

**Comment by Prinzhorn** [comment]
1. The docs say "A string used for your CSS sourcemap.", I'm not sure what that's supposed to mean, but it doesn't sound like it means what you think it does
2. If you search the Svelte code it appears `cssOutputFilename` is actually not implemented. I found this https://github.com/sveltejs/svelte/pull/5754#issuecomment-743146601 "(1) option.cssOutputFilename is never used. I guess it should be passed to stylesheet.render instead of option.filename (with fallback to it) when options.css != true.". Not sure if that's still accurate, but like I said, the Svelte source is literally never using `cssOutputFilename`

**Comment by Mytakeon** [comment]
Ah, I see, I opened the issue here but wasn't sure if it could be related to esbuild-svelte. Thanks for the hints!
