### ISSUE TITLE
External Svelte module errors when using a Svelte import

### ISSUE THREAD

**Issue by NotSpaulding** [EMH333/esbuild-svelte#174]
**Describe the bug**
If you use onMount (or most likely any Svelte import) with Svelte being external (by doing something like `external: ['./node_modules/*']` in your build config) you get the following error:
```
svelte@3.57.0/node_modules/svelte/internal/index.mjs:1050 Uncaught (in promise) Error: Function called outside component initialization
    at get_current_component (svelte@3.57.0/node_modules/svelte/internal/index.mjs:1050)
    at onMount (svelte@3.57.0/node_modules/svelte/internal/index.mjs:1073)
    ...
```

**To Reproduce**

1. Add `external: ['./node_modules/*']` to your esbuild config
2. Use onMount (or most likely any other Svelte import) in a `.svelte` file

**Expected behavior**
The error doesn't appear

**Environment (please complete the following information):**

- esbuild-svelte version: 0.7.3
- esbuild version: 0.17.11
- Svelte preprocessors used (if any): svelte-preprocess@5.0.3

**Additional notes**
I am compiling to ESM

**Comment by EMH333** [comment]
I am unable to replicate this when compiling the [`example-js`](https://github.com/EMH333/esbuild-svelte/tree/main/example-js) project (updated to same `esbuild`, `esbuild-svelte` and `svelte` versions you are using) with `external: ['./node_modules/*']`. Or more exactly, I see the `the second component has mounted` log output in my browser which is expected if `onMount` has been run correctly.

Can you provide a more complete reproduction?

**Comment by EMH333** [comment]
I can say with a fair amount of confidence that your custom esbuild plugin `ESM module resolver` is what is causing this issue. If I look at the bundled `renderer.js` file without minification, I can see the `noop` function from svelte/internal is included in the file, then also imported as `noop2` later on. This hints at multiple copies of Svelte's runtime being included/imported. 

When I remove that custom plugin, I see a single copy of the svelte/internal functions being imported.

As such, I believe this issue is out of scope for this repo and I'll go ahead and close it in the next few days.
