### ISSUE TITLE
Updating examples to use the 0.17.x esbuild "context API"?

### ISSUE THREAD

**Issue by silverdr** [EMH333/esbuild-svelte#180]
**Is your feature request related to a problem? Please describe.**
Updating esbuild to any of the 0.17 versions breaks "watch mode". This is described in the esbuild documentation that the option was simply removed for ... reasons

**Describe the solution you'd like**
I would like to be able to properly use "watch" mode again after updating esbuild to 0.17.x or later. It probably doesn't require any changes to esbuild-svelte (I guess ?) but rather to example `buildscript.js` files

**Comment by EMH333** [comment]
Yes I should probably update that example. The reason I've been holding off is because esbuild 0.17.x breaks the auto-magical caching logic that esbuild-svelte uses. I'm still holding out hope for https://github.com/evanw/esbuild/issues/2823 to be acted upon so that can continue.

I'll see if I have some time soon to get this plugin updated w/ 0.17 examples.

**Comment by silverdr** [comment]
That would be totally awesome ;-)

**Comment by EMH333** [comment]
esbuild now supports the context API internally and enough time has passed that there are examples online of how to use the context API for building. If you are having specific trouble, feel free to open a [discussion](https://github.com/EMH333/esbuild-svelte/discussions), and we can work from there.

I'm considering this issue closed
