### ISSUE TITLE
Svelte on m1 bug with precompiled svelte/internal sources.

### ISSUE THREAD

**Issue by Valexr** [EMH333/esbuild-svelte#23]
Svelte on m1 bug with precompiled svelte/internal sources.
When component unmount from slot i have this error:

![image](https://user-images.githubusercontent.com/5656366/105285336-3f15a480-5bc5-11eb-8448-7f84098ea4ce.png)

When un/mount component in slot in localy imported module with this file structure:

- distImportedModule
- srcImportedModule
   - app
      - distApp
      - srcApp
 
 
![image](https://user-images.githubusercontent.com/5656366/105284722-18a33980-5bc4-11eb-9bf2-66d602c5e0fb.png)

### TESTED SOURCES ONLY FOR M1 arm64 architecture

[Source code](https://svelte.dev/repl/d6af19f0af41493f9f31e54cd75a96ea) for example. 
If you download it - remove rollup bundler.

Or [zip](https://github.com/Valexr/svelte-slidy/blob/master/tmp/svelte-slidy.zip) example.

**Comment by EMH333** [comment]
Any particular reason you also opened an issue with esbuild (https://github.com/evanw/esbuild/issues/699)? Unless there is something clear that points to an issue within esbuild itself, it likely won't be the place to find a solution.

This sort of error hints at problems importing a svelte module. The source code, file structure and zip you included seem to be three completely different projects (one is **using** svelte-slidy, the another **is** svelte-slidy from what I can tell) so I'm having a hard time determining exactly where the problem is and what to look for. Some guidance here would be very helpful.

I would confirm that all the required svelte modules are being imported correctly. If you are attempting to create a node library or package, set the `platform` esbuild option to `'node'` which will not bundle modules in `node_modules`. Then, for the actual application being served to users, I would highly recommend allowing the svelte sources to be bundled (`platform: 'browser'`).

**Comment by Valexr** [comment]
Bug in svelte/internal/index.mjs file - this expression not working properly in esbuild bundle on m1 mac arm64 processor. But strange, it`s working on x86 architecture 🤷🏻‍♂️

if you have arm64 m1 mac - you can see this issue in .zip 

![91680814-7dc59800-eb1a-11ea-8698-16aba1aeba67](https://user-images.githubusercontent.com/5656366/105398229-2643d800-5c33-11eb-9604-b2b58872f64e.png)

**Comment by Valexr** [comment]
> Any particular reason you also opened an issue with esbuild ([evanw/esbuild#699](https://github.com/evanw/esbuild/issues/699))? Unless there is something clear that points to an issue within esbuild itself, it likely won't be the place to find a solution.
> 
> This sort of error hints at problems importing a svelte module. The source code, file structure and zip you included seem to be three different projects (one is **using** svelte-slidy, the another **is** svelte-slidy from what I can tell) so I'm having a hard time determining exactly where the problem is and what to look for. Some guidance here would be very helpful.
> 
> I would confirm that all the required svelte modules are being imported correctly. If you are attempting to create a node library or package, set the `platform` esbuild option to `'node'`. Then, for the actual application being served to users, I would highly recommend allowing the svelte sources to be bundled (`platform: 'browser'` and remove them from `external`).

**Comment by EMH333** [comment]
Interesting! I'm glad you were able to find the root source of the problem!

**Comment by Valexr** [comment]
> Interesting! I'm glad you were able to find the root source of the problem!

Me too very interesting )))

Which format you are recommend for platform browser?

**Comment by EMH333** [comment]
It's surprising that you are seeing a difference based on architecture. That shouldn't be the case. Are you sure your environments are identical?

IIFE (the default) is probably fine, that is what Evan recommends and it should see a few optimizations in the next few months

**Comment by Valexr** [comment]
Yep! Environments are identical. Only different processors.🤷🏻

**Comment by Valexr** [comment]
Tx for @AlexxNB for advice & help 👍🏻 
His fix when m1 missed svelte package path for esbuild:

```js
function fix_svelte_path() {
    return {
        name: 'fix_svelte_path',
        setup(b) {
			const path = require('path')
            b.onResolve({ filter: /^svelte$|^svelte\// }, args => {
                return { path: path.join(__dirname,'node_modules',args.path,'index.mjs') }
            });
        }
    }
}
```
