### ISSUE TITLE
Can't resolve fakecss-path with splitting: true

### ISSUE THREAD

**Issue by Valexr** [EMH333/esbuild-svelte#41]
One more time ))) I just want explain situation:

I have splitting bundles with css-chunks, but i can't load css on page...

![Screenshot 2021-03-21 at 10 01 24](https://user-images.githubusercontent.com/5656366/111896728-9f418f00-8a2c-11eb-9d30-f758a7e31540.jpg)

index.js
![Screenshot 2021-03-21 at 10 09 45](https://user-images.githubusercontent.com/5656366/111896886-a4530e00-8a2d-11eb-90a5-710e2dc45449.jpg)

index.css
![Screenshot 2021-03-21 at 10 09 19](https://user-images.githubusercontent.com/5656366/111896889-acab4900-8a2d-11eb-8b6c-f6f781507b60.jpg)

I have some resolver for this, but its not working with splitting: true...

```js
let fakecsspathResolvePlugin = {
    name: 'fakecsspath',
    setup(build) {
        let path = require('path')

        build.onResolve({ filter: /\.esbuild-svelte-fake-css$/ }, ({ path }) => {
            return { path, namespace: 'fakecss' }
        })

        build.onLoad({ filter: /\.esbuild-svelte-fake-css$/, namespace: 'fakecss' }, ({ path }) => {
            const css = cssCode.get(path);
            return css ? { contents: css, loader: "css" } : null;
        })
    },
}
```

**Comment by Valexr** [comment]
may be need use `namespace: 'file'` ?

**Comment by EMH333** [comment]
Certainly something to try. I currently use the `fakecss` namespace because the css files don't exist on the actual file system, the plugin creates them on a virtual filesystem. From the [esbuild documentation](https://esbuild.github.io/plugins/#namespaces):
> By default esbuild operates in the file namespace, which corresponds to files on the file system. But esbuild can also handle "virtual" modules that don't have a corresponding location on the file system.
> ...
> Virtual modules usually use a namespace other than file to distinguish them from file system modules.

In this case, I consider the fake css to be a virtual module and thus use a different namespace. Can you please clarify where Evan recommends the file namespace?


Additionally can you please clarify what you mean when you say
> when `//fake-css` includes links in single css/js file it's work ok...

Something you could try would be to replace the `fakecss` namespace in the `dist/index.js` / `dist/index.mjs` files of this plugin with `file` and see if that makes a difference. If it does, report back and we can talk about what that looks like. 

I'm also confused why there is a need for the `fakecsspathResolvePlugin`.

**[esbuild does not support css splitting at the moment](https://github.com/evanw/esbuild/issues/20#issuecomment-803527200)** and that isn't something that I want to attempt to solve with this plugin at the moment. You could [disable css file output](https://github.com/EMH333/esbuild-svelte#css-output) from Svelte which isn't ideal but might go a long way towards solving this for now.

**Comment by Valexr** [comment]
> Certainly something to try. I currently use the `fakecss` namespace because the css files don't exist on the actual file system, the plugin creates them on a virtual filesystem. From the [esbuild documentation](https://esbuild.github.io/plugins/#namespaces):
> 
> > By default esbuild operates in the file namespace, which corresponds to files on the file system. But esbuild can also handle "virtual" modules that don't have a corresponding location on the file system.
> > ...
> > Virtual modules usually use a namespace other than file to distinguish them from file system modules.
> 
> In this case, I consider the fake css to be a virtual module and thus use a different namespace. Can you please clarify where Evan recommends the file namespace?

https://github.com/evanw/esbuild/issues/808#issuecomment-806087899

> 
> Additionally can you please clarify what you mean when you say
> 
> > when `//fake-css` includes links in single css/js file it's work ok...
> 
> Something you could try would be to replace the `fakecss` namespace in the `dist/index.js` / `dist/index.mjs` files of this plugin with `file` and see if that makes a difference. If it does, report back and we can talk about what that looks like.
> 
> I'm also confused why there is a need for the `fakecsspathResolvePlugin`.
> 
> **[esbuild does not support css splitting at the moment](https://github.com/evanw/esbuild/issues/20#issuecomment-803527200)** and that isn't something that I want to attempt to solve with this plugin. You could [disable css file output](https://github.com/EMH333/esbuild-svelte#css-output) from Svelte which isn't ideal but might go a long way towards solving this for now.

**Comment by Valexr** [comment]
https://github.com/evanw/esbuild/issues/808#issuecomment-806087899

has no effect

**Comment by EMH333** [comment]
ah! I just realized that you are wanting to automatically import the generated css files from js! You gave the problems you were having but not the expected outcome

esbuild has a few breaking changes that are about to be released that should make this easier. Pretty sure this is now a feature request given that importing the css files from js **isn't something this plugin currently supports**. If that isn't correct please feel free to correct me!

**Comment by Valexr** [comment]
Today new release 0.12.0 fix it 👍🏻
I’m m happy 🤓

**Comment by EMH333** [comment]
Awesome glad to hear it!
